[build-system]
requires = ["poetry>=1.6"]
build-backend = "poetry.masonry.api"

[tool.black]
line-length = 96
target-version = ['py311']

[project]
name = "fondat"
version = "4.2.0"
description = "A foundation for resource-oriented backend applications."
readme = "README.md"
authors = [
    { name = "Paul Bryan", email = "pbryan@anode.ca" }
]
license = "MIT"
keywords = ["asgi", "foundation", "resource", "openapi"]
classifiers = [
    "Development Status :: 5 - Production/Stable",
    "Intended Audience :: Developers",
    "Topic :: Software Development :: Libraries :: Application Frameworks",
]
requires-python = ">=3.11"
dependencies = [
    "aiosqlite (>=0.21.0,<0.22.0)",
    "iso8601 (>=2.1.0,<3.0.0)",
    "multidict (>=6.7.0,<7.0.0)",
    "wrapt (>=1.17.3,<2.0.0)", 
]

[project.urls]
homepage = "https://github.com/fondat/fondat/"
documentation = "https://github.com/fondat/fondat/tree/main/docs"

[tool.poetry]
packages = [
    { include = "fondat" }
]
requires-poetry = ">=2.0"

[tool.poetry.dependencies]
python = ">=3.11,<3.13"

[tool.isort]
profile = "black"
lexicographical = true
lines_after_imports = 2
lines_between_types = 1
line_length = 96
no_sections = true

[tool.pytest.ini_options]
asyncio_mode = "auto"

[dependency-groups]
test = [
    "pytest (>=8.4.2,<9.0.0)",
    "black (>=25.9.0,<26.0.0)",
    "isort (>=7.0.0,<8.0.0)",
    "pre-commit (>=4.3.0,<5.0.0)",
    "pytest-asyncio (>=1.2.0,<2.0.0)",
    "pytest-cov (>=7.0.0,<8.0.0)"
]
